### ISSUE TITLE
下滑松开，顶部消失太快

### ISSUE THREAD

**Issue by zhongxiong00** [ashqal/ChromeLikeSwipeLayout#1]
下滑松开，顶部消失太快，公开一个方法，设置一下消失时间吧。

**Comment by ashqal** [comment]
as you wish ^_^

**Comment by zhongxiong00** [comment]
ok,thank you very much...  you are a chiness?

**Comment by ashqal** [comment]
是啊。。不然我怎么看得懂中文。。哈哈哈哈哈哈

**Comment by zhongxiong00** [comment]
那你还 as you wish.哈哈哈

**Comment by ashqal** [comment]
我憋了很久才想出这个词的 为了international啊

**Comment by TakWolf** [comment]
你们俩太逗了....233333

**Comment by zhongxiong00** [comment]
添加一个触发下拉刷新的方法吧。不用手滑也可以下拉。

**Comment by ashqal** [comment]
有这样的应用场景吗？因为这个和下拉刷新不同，它是下拉执行更多的操作，就算选到了刷新，也是立即回弹了

**Comment by zhongxiong00** [comment]
默认就是回调中间的刷新。

**Comment by zhongxiong00** [comment]
不是有动画显示时间设置么。

**Comment by ashqal** [comment]
这个时间是不靠谱的，你无法确定网络请求是多少秒返回。这个库更倾向于选择操作＝》回弹＝》执行操作，你说的可能是选择操作＝》执行操作＝》回弹

**Comment by ashqal** [comment]
你说的那种交互逻辑也是可以实现的，未来我加个分支，选择操作＝》执行操作＝》菊花转＝》执行成功回调＝》回弹

**Comment by zhongxiong00** [comment]
可以。
