### ISSUE TITLE
compile 'com.github.ashqal:ChromeLikeSwipeLayout:0.4' gives "Failed to resolve"

### ISSUE THREAD

**Issue by nominalista** [ashqal/ChromeLikeSwipeLayout#11]
Or maybe I am doing something wrong ?

**Comment by ashqal** [comment]
Did you forget to add `jitpack repository url` to your `/build.gradle`

``` java
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by nominalista** [comment]
There was something wrong with my Intellij, but thanks for time. It's beautifully working.
