### ISSUE TITLE
Nested RecyclerView fails to scroll

### ISSUE THREAD

**Issue by mradzinski** [ashqal/ChromeLikeSwipeLayout#2]
Given the following layout RecyclerView fails to scroll up:

```
FrameLayout
    com.asha.ChromeLikeSwipeLayout
        android.support.percent.PercentRelativeLayout
            android.support.v7.widget.RecyclerView
            ...
```

I think it's due to the fact you only take into account the first child of ChromeLikeSwipeLayout to check if it's scrollable or not. This kind of situation must be taken into account since having a layout with a nested RecylcerView it's quite a common scenario.

**Comment by ashqal** [comment]
Confirmed. I will figure it out ASAP. Thank you.
